### ISSUE TITLE
ELB Aplication type doesn't work

### ISSUE THREAD

**Issue by dartua** [wawastein/zabbix-cloudwatch#2] opened 2017-06-14 15:11 UTC
Hi,

I'v created template based on your script, but when I'm using "AWS/ApplicationELB" namespace I get error "Received value [-1] is not suitable for value type [Numeric (unsigned)] and data type [Decimal"

![image](https://user-images.githubusercontent.com/9005237/27139886-d79782d4-512c-11e7-8735-846fdf0b91c6.png)

**Comment by wawastein** [comment] 2017-06-14 16:05
Duplicate of #1

**Closed** 2017-06-14 16:04 UTC
